# Generated by Django 2.0 on 2018-09-11 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=40)),
                ('event_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('event_name',),
            },
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer_handle', models.CharField(max_length=50)),
                ('legal_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mailing_address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('shirt', models.CharField(blank=True, choices=[('XS', 'X Small'), ('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Large'), ('XL', 'X Large'), ('2X', '2X Large'), ('3X', '3X Large'), ('4X', '4X Large'), ('5X', '5X Large')], default='XL', max_length=2)),
                ('country', models.CharField(blank=True, choices=[('USA', 'United States'), ('CAN', 'Canada'), ('UNK', 'United Kingdom'), ('SAM', 'South America'), ('FRA', 'France'), ('ASN', 'Asia'), ('OEU', 'Europe'), ('OTH', 'Other')], default='USA', max_length=3)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('youtube', models.CharField(blank=True, max_length=50)),
                ('twitch', models.CharField(blank=True, max_length=50)),
                ('mixer', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('events', models.ManyToManyField(blank=True, to='mainApp.Events')),
            ],
            options={
                'ordering': ('influencer_handle',),
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('list_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('list_name', models.CharField(max_length=50)),
                ('list_influencers', models.ManyToManyField(blank=True, to='mainApp.Influencer')),
                ('list_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('list_name',),
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=40)),
                ('tag_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('tag_name',),
            },
        ),
        migrations.AddField(
            model_name='influencer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mainApp.Tags'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
